volumes:
  pg_data:

services:
  redis:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379

  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  fastapi_app:
    env_file: .env
    build: ./fastapi_app/
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis

  gateway:
    build: ./gateway/
    ports:
      - 80:80
    depends_on:
      - db
      - fastapi_app
